context:
  name: pixi-outdated
  version: "0.1.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/benmoss/${{ name }}/archive/v${{ version }}.tar.gz
  sha256: 4cc91103d74afdb7d2217566870cc53d1fad943062dc2fef4a64ec1d72ec3d25

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses

tests:
  - script:
      - pixi-outdated --version

about:
  homepage: https://github.com/benmoss/pixi-outdated
  summary: A CLI tool to check for outdated dependencies in pixi projects.
  description: |
    A CLI tool to check for outdated dependencies in pixi projects.
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  repository: https://github.com/benmoss/pixi-outdated

extra:
  recipe-maintainers:
    - benmoss
